#!/usr/bin/env node
/**
 * Pre-build step: reads src/admin/ui.js and writes src/admin/ui-bundle.js,
 * which exports the UI source as a string literal. This lets us inline the
 * admin SPA inside the handler bundle so it doesn't need filesystem access at
 * runtime — important for environments like Next.js where the handler is
 * bundled into .next/server/* but the UI file is not co-located.
 *
 * Run automatically by `npm run build` (and the dev / watch path) via the
 * `prebuild` and `predev` scripts.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const src = resolve(repoRoot, 'src/admin/ui.js');
const dest = resolve(repoRoot, 'src/admin/ui-bundle.js');

const content = await readFile(src, 'utf8');
const output =
  `// Auto-generated by scripts/inline-ui.js — do not edit.\n` +
  `// Source: src/admin/ui.js (${content.length} chars)\n\n` +
  `export const UI_JS_BUNDLE = ${JSON.stringify(content)};\n`;
await mkdir(dirname(dest), { recursive: true });
await writeFile(dest, output, 'utf8');
process.stdout.write(`✓ inlined ${src} → ${dest} (${content.length} chars)\n`);
